# Generated by Django 6.0.5 on 2026-05-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipr_aligned_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=2, help_text='1=Easy … 5=Expert'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
