# Generated by Django 6.0.5 on 2026-05-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_add_category_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, default='', help_text='e.g. Egyptian, Italian', max_length=50),
        ),
    ]
